package com.liyaqa.backend.internal.audit.domain

enum class AuditAction {
    // Authentication
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    
    // Employee Management
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_SUSPENDED,
    EMPLOYEE_REACTIVATED,
    EMPLOYEE_DELETED,
    EMPLOYEE_GROUP_ASSIGNED,
    EMPLOYEE_GROUP_REMOVED,
    EMPLOYEE_LOGIN,
    
    // Tenant Operations
    TENANT_CREATED,
    TENANT_UPDATED,
    TENANT_SUSPENDED,
    TENANT_REACTIVATED,
    TENANT_DELETED,
    TENANT_DATA_ACCESSED,
    TENANT_IMPERSONATED,
    
    // Support Actions
    TICKET_VIEWED,
    TICKET_ASSIGNED,
    TICKET_RESOLVED,
    TICKET_ESCALATED,
    
    // Financial Operations
    DEAL_CREATED,
    DEAL_UPDATED,
    DEAL_APPROVED,
    DEAL_REJECTED,
    PAYMENT_PROCESSED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    
    // System Operations
    CONFIGURATION_CHANGED,
    MAINTENANCE_MODE_ENABLED,
    MAINTENANCE_MODE_DISABLED,
    DATA_EXPORTED,
    DATA_IMPORTED,
    
    // Security Events
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    SUSPICIOUS_ACTIVITY_DETECTED,
    API_KEY_CREATED,
    API_KEY_REVOKED,
}